import janken from "@/constants/janken.js";
export const type = {
    attack: 1,
    defense: 2,
    balance: 3,
    superAttack: 4,
    superDefense: 5,
}
export const kabutoMushi = {
    id: "allomyrina_dichotoma",
    name: "カブトムシ",
    src: "kabutomushi.jpg",
    weapon: janken.paa,
    basePower: 120,
    hp: 100,
    guu: 35,
    choki: 35,
    paa: 70,
    technique: 90,
    type: type.attack,
    special: "tornade_throw",
}
export const nokogiriKuwagata = {
    id: "prosopocoilus_inclinatus",
    name: "ノコギリクワガタ",
    src: "nokogirikuwagata.jpg",
    weapon: janken.choki,
    basePower: 120,
    hp: 100,
    guu: 35,
    choki: 70,
    paa: 35,
    technique: 90,
    type: type.attack,
    special: "running_cutter",
}
export const anubisZouKabuto = {
    id: "megasoma_anubis",
    name: "アヌビスゾウカブト",
    src: "anubis_zou_kabuto.jpg",
    weapon: janken.guu,
    basePower: 140,
    hp: 120,
    guu: 80,
    choki: 40,
    paa: 40,
    technique: 70,
    type: type.attack,
    special: "submarine_attack",
}
export const arukidesOohirataKuwatata = {
    id: "dorcus_alcides",
    name: "アルキデスオオヒラタクワガタ",
    src: "arukides_oohirata_kuwagata.jpg",
    weapon: janken.guu,
    basePower: 160,
    hp: 120,
    guu: 100,
    choki: 50,
    paa: 50,
    technique: 60,
    type: type.superAttack,
    special: "complete_smash",
}
export const atlasOokabuto = {
    id: "chalcosoma_atlas",
    name: "アトラスオオカブト",
    src: "atlas_ookabuto.jpg",
    weapon: janken.paa,
    basePower: 140,
    hp: 120,
    guu: 40,
    choki: 40,
    paa: 80,
    technique: 70,
    type: type.attack,
    special: "side_screw_throw",
}
export const centaurusOokabuto = {
    id: "augosoma_centaurus",
    name: "ケンタウルスオオカブト",
    src: "centaurus_ookabuto.jpg",
    weapon: janken.paa,
    basePower: 140,
    hp: 140,
    guu: 35,
    choki: 35,
    paa: 70,
    technique: 70,
    type: type.balance,
    special: "cyclone_whip",
}
export const erafusHosoakaKuwagata = {
    id: "cyclommatus_elaphus",
    name: "エラフスホソアカクワガタ",
    src: "erafus_hosoaka_kuwagata.jpg",
    weapon: janken.choki,
    basePower: 100,
    hp: 100,
    guu: 25,
    choki: 50,
    paa: 25,
    technique: 100,
    type: type.balance,
    special: "kawasemi_hug",
}
export const faburisNokogiriKuwagata = {
    id: "prosopocolius_fabricei",
    name: "ファブリースノコギリクワガタ",
    src: "faburis_nokogiri_kuwagata.jpg",
    weapon: janken.choki,
    basePower: 100,
    hp: 60,
    guu: 35,
    choki: 70,
    paa: 35,
    technique: 100,
    type: type.superAttack,
    special: "hayabusa",
}
export const gurantShiroKabuto = {
    id: "dynastes_granti",
    name: "グラントシロカブト",
    src: "granto_shiro_kabuto.jpg",
    weapon: janken.paa,
    basePower: 100,
    hp: 100,
    guu: 25,
    choki: 25,
    paa: 50,
    technique: 100,
    type: type.balance,
    special: "tornade_throw",
}
export const himeKabuto = {
    id: "xylotrupes_gideon",
    name: "ヒメカブト",
    src: "hime_kabuto.jpg",
    weapon: janken.guu,
    basePower: 100,
    hp: 80,
    guu: 60,
    choki: 30,
    paa: 30,
    technique: 100,
    type: type.attack,
    special: "hayate",
}
export const hirataKuwagata = {
    id: "dorcus_titanus",
    name: "ヒラタクワガタ",
    src: "hirata_kuwagata.jpg",
    weapon: janken.choki,
    basePower: 120,
    hp: 100,
    guu: 35,
    choki: 70,
    paa: 35,
    technique: 90,
    type: type.attack,
    special: "kawasemi_hug",
}
export const hirutusHerazunoKabuno = {
    id: "heterogomphus_hirtus",
    name: "ヒルトゥスヘラヅノカブト",
    src: "hirutus_herazuno_kabuno.jpg",
    weapon: janken.paa,
    basePower: 120,
    hp: 120,
    guu: 30,
    choki: 30,
    paa: 60,
    technique: 90,
    type: type.balance,
    special: "daisharin",
}
export const hyllusShiroKabuto = {
    id: "hynastes_hyllus",
    name: "ヒルスシロカブト",
    src: "hyllus_shiro_kabuto.jpg",
    weapon: janken.paa,
    basePower: 160,
    hp: 180,
    guu: 35,
    choki: 35,
    paa: 70,
    technique: 60,
    type: type.defense,
    special: "da_vuelta",
}
export const inperialisTsuyaKuwagata = {
    id: "odontolabius_imperialis",
    name: "インペリアリスツヤクワガタ",
    src: "inperialis_tsuya_kuwagata.jpg",
    weapon: janken.choki,
    basePower: 120,
    hp: 140,
    guu: 25,
    choki: 50,
    paa: 25,
    technique: 90,
    type: type.defense,
    special: "forest_bridge",
}
export const kogashiraKuwagata = {
    id: "chiasognathus_grantii",
    name: "コガシラクワガタ",
    src: "kogashira_kuwagata.jpg",
    weapon: janken.choki,
    basePower: 140,
    hp: 140,
    guu: 35,
    choki: 70,
    paa: 35,
    technique: 70,
    type: type.balance,
    special: "devil_sleeper",
}
export const kokuwagata = {
    id: "dorcus_rectus",
    name: "コクワガタ",
    src: "kokuwagata.jpg",
    weapon: janken.guu,
    basePower: 100,
    hp: 120,
    guu: 40,
    choki: 20,
    paa: 20,
    technique: 100,
    type: type.defense,
    special: "rolling_smash",
}
export const lacodarTsuyaKuwagata = {
    id: "odontolabis_lacordairei",
    name: "ラコダールツヤクワガタ",
    src: "lacodar_tsuya_kuwagata.jpg",
    weapon: janken.choki,
    basePower: 160,
    hp: 160,
    guu: 40,
    choki: 80,
    paa: 40,
    technique: 60,
    type: type.balance,
    special: "devil_sleeper",
}
export const maximusMarubaneKuwagata = {
    id: "neolucanus_maximus",
    name: "マキシムスマルバネクワガタ",
    src: "maximus_marubane_kuwagata.jpg",
    weapon: janken.guu,
    basePower: 120,
    hp: 100,
    guu: 70,
    choki: 35,
    paa: 35,
    technique: 90,
    type: type.attack,
    special: "hayate",
}
export const miyamaKuwagata = {
    id: "lucanus_maculifemoratus",
    name: "ミヤマクワガタ",
    src: "miyama_kuwagata.jpg",
    weapon: janken.choki,
    basePower: 140,
    hp: 120,
    guu: 40,
    choki: 80,
    paa: 40,
    technique: 70,
    type: type.attack,
    special: "rolling_clutch_hold",
}
export const moelienkampOokabuto = {
    id: "chalcosoma_moellenkampi",
    name: "モーレンカンプオオカブト",
    src: "moelienkamp_ookabuto.jpg",
    weapon: janken.paa,
    basePower: 160,
    hp: 140,
    guu: 45,
    choki: 45,
    paa: 90,
    technique: 60,
    type: type.attack,
    special: "cyclone_whip",
}
export const neptuneOokabuto = {
    id: "dynastes_neptunus",
    name: "ネプチューンオオカブト",
    src: "neptune_ookabuto.jpg",
    weapon: janken.paa,
    basePower: 160,
    hp: 160,
    guu: 40,
    choki: 40,
    paa: 80,
    technique: 60,
    type: type.balance,
    special: "side_screw_throw",
}

export const ookuwagata = {
    id: "dorcus_hopei_binodulosus",
    name: "オオクワガタ",
    src: "ookuwagata.jpg",
    weapon: janken.guu,
    basePower: 140,
    hp: 160,
    guu: 60,
    choki: 30,
    paa: 30,
    technique: 70,
    type: type.defense,
    special: "dragon_attack",
}
export const sabiiroKabuto = {
    id: "allomyrina_pfeifferi_celebensis",
    name: "サビイロカブト",
    src: "sabiiro_kabuto.jpg",
    weapon: janken.paa,
    basePower: 100,
    hp: 120,
    guu: 20,
    choki: 20,
    paa: 40,
    technique: 100,
    type: type.defense,
    special: "daisharin",
}
export const satanOokabuto = {
    id: "dynastes_satanas",
    name: "サタンオオカブト",
    src: "satan_ookabuto.jpg",
    weapon: janken.paa,
    basePower: 180,
    hp: 220,
    guu: 35,
    choki: 35,
    paa: 70,
    technique: 40,
    type: type.superDefense,
    special: "s_a_s",
}
export const speciosusShikaKuwagata = {
    id: "rhaetulus_speciosus",
    name: "スぺキオシスシカクワガタ",
    src: "speciosus_shika_kuwagata.jpg",
    weapon: janken.choki,
    basePower: 100,
    hp: 120,
    guu: 20,
    choki: 40,
    paa: 20,
    technique: 100,
    type: type.defense,
    special: "running_cutter",
}
export const thaiGohonzunoKabuto = {
    id: "eupatorus_siamensis",
    name: "タイゴホンヅノカブト",
    src: "thai_gohonzuno_kabuto.jpg",
    weapon: janken.paa,
    basePower: 120,
    hp: 120,
    guu: 30,
    choki: 30,
    paa: 60,
    technique: 90,
    type: type.balance,
    special: "side_rock_bomb",
}
export const mushiking = {
    id: "mushi_king",
    name: "ムシキング",
    src: "mushi_king.jpg",
    weapon: janken.paa,
    basePower: 160,
    hp: 160,
    guu: 40,
    choki: 40,
    paa: 80,
    technique: 60,
    type: type.balance,
    special: "king_tornade_throw",
}
export const chanG = {
    id: "chan_g",
    name: "チャン G（ムナコブクワガタ）",
    src: "chan_g.jpg",
    weapon: janken.guu,
    basePower: 120,
    hp: 120,
    guu: 40,
    choki: 20,
    paa: 20,
    technique: 100,
    type: type.defense,
    special: "kagerou",
}

export const mushis = [
    kabutoMushi,
    nokogiriKuwagata,
    anubisZouKabuto,
    arukidesOohirataKuwatata,
    atlasOokabuto,
    centaurusOokabuto,
    erafusHosoakaKuwagata,
    gurantShiroKabuto,
    faburisNokogiriKuwagata,
    himeKabuto,
    hirataKuwagata,
    hirutusHerazunoKabuno,
    hyllusShiroKabuto,
    inperialisTsuyaKuwagata,
    kogashiraKuwagata,
    kokuwagata,
    lacodarTsuyaKuwagata,
    maximusMarubaneKuwagata,
    miyamaKuwagata,
    moelienkampOokabuto,
    neptuneOokabuto,
    ookuwagata,
    sabiiroKabuto,
    satanOokabuto,
    speciosusShikaKuwagata,
    thaiGohonzunoKabuto,
    mushiking,
    chanG
]